name: github_trend_summary
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  args: ^2.4.0
  http: ^1.1.0
  xml: ^6.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
